### ISSUE TITLE
Solucionado

### ISSUE THREAD

**Issue by ffcadenas** [RubenGamezTorrijos/Wibeee-Smilics-Circutor-API-Local#1]
Al importar el json figura el siguiente error

SyntaxError: Unexpected token in JSON at position 2075
"wibeee ={};↵ \nwibeee.V

Gracias es muy interesante este desarrollo

![image](https://user-images.githubusercontent.com/59702266/133526902-09fb1ccd-e2a5-43b3-89df-1288dd935440.png)

**Comment by RubenGamezTorrijos** [comment]
El JSON no es el mismo porque no es llegar y pegar. Debes obtener los datos de tu propio Wibeee y hay muchos modelos.

El que tengo es de 2016 y el firmware sino recuerdo mal v.3.6xxx creo. Y el Wibeee usa la App de circutor o wibeee business.

Si tienes nodered con Get introduces la URL que aparece el repositorio y añades un debug y lo tienes. En mi caso funciona correctamente, tanto El antiguo como los actuales, pero la versión JSON son distintas.

Animo y a trabajarlo. 👍😊
Gracias

**Comment by RubenGamezTorrijos** [comment]
Subido el flow de Node-Red. Ya pueden importar los siguientes datos y funciones en JavaScript para que cada usuario personalice según su versión de Wibeee, dependiendo del firmware del dispositivos, los parámetros cambian. En mi caso tengo la versión Circutor, y es de los primeros que salieron por el año 2015.

**Comment by RubenGamezTorrijos** [comment]
flow.json  Solucionado.
